"""create access event schema

Revision ID: e19c06653229
Revises: 2c6a2a716b6d
Create Date: 2026-06-15 12:04:48.203269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e19c06653229'
down_revision: Union[str, Sequence[str], None] = '2c6a2a716b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_access_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'event_ts', 'direction', name='uq_access_event')
    )
    op.create_index('ix_person_event_ts', 'fact_access_event', ['person_id', 'event_ts'], unique=False)
    op.create_table('raw_access_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_access_events')
    op.drop_index('ix_person_event_ts', table_name='fact_access_event')
    op.drop_table('fact_access_event')
    # ### end Alembic commands ###
